### ISSUE TITLE
Unexpected behavior when project name includes text enclosed in parentheses

### ISSUE THREAD

**Issue by solarlight2** [Algomorph/CodeGrader#131]
**Describe the bug**
Suppose a project/assignment name on the submit server contains parentheses, and so you assign the JSON option "submitServerAssignmentName" to be that name. The comparing of headerText to submitServerAssignmentName has unexpected results (namely, it fails) because JavaScript .match interprets submitServerAssignmentName as a regex expression and the comparison fails since the parentheses are not matched (thing in parentheses is interpreted as a capturing group rather as text enclosed in parentheses).

**Where did the bug occur**
Instructor & Course: [Fawzi CMSC131]
Project name on Submit Server: [P2 (Maryland Baseball)]

**Desktop (please complete the following information):**
 - OS: Windows

**Additional info**
I imagine this may also occur if project names include text with other regex characters, and you try to enter that name as the submitServerAssignmentName. I think submitServerAssignmentName (any anything else being matched) should be escaped first before being used in .match, since .match converts the argument to a RegExp.

**Comment by Algomorph** [comment]
You're right, the matching for the project name on the Submit Server does not take regex characters in the name into account.
The culprit is this line:
https://github.com/Algomorph/CodeGrader/blob/c4e01c94fba2d0bb4d87fbe28854e8bd1746c0a3/submit_server_main.js#L48

Is it possible for you to work around this currently by escaping the "(" and ")" in the name, e.g. setting up the project with
"P2 \(Maryland Baseball\)" or "P2 \\(Maryland Baseball\\)"?

I will also try to fix this on my end, but I will have to do so blindly, without concrete test cases, since I don't have access to Fawzi's CMSC131 on the Submit Server currently.

**Comment by Algomorph** [comment]
Yes, I just tested, `"P2 \\(Maryland Baseball\\)"` should work when you are grading individual submissions. It's still a crude work-around, though, so I'll come up with a fix right now.

**Comment by Algomorph** [comment]
Fixed in e1639dd259a5b6946bf81a394177c7eb2cfd87ce
