### ISSUE TITLE
Testing Module: Issue with Inheritance

### ISSUE THREAD

**Issue by msimmon6** [Algomorph/CodeGrader#173]
**Describe the bug**

The testing module does not pick up the method called when static type is not as expected.

**Where did the bug occur**

Semester: Spring 2022
Instructor & Course: Pedram's CMSC131
Project name on Submit Server: Proj 8
Student directory id: dwu1

Code segment (if known & relevant):
@Test
    public void TestFlag() {  
        Diagram flag = new Flag(sizeFlag, color4, color2, color3, animationType); 
        board = flag.getBoard();                                                                             // Should say it tests Flag::getBoard
        result1 += "\n" + getFlagArray(board); 
        board = flag.nextAnimationStep();                                                             // Should say it tests Flag::nextAnimationStep
        result2 += "\n"+getFlagArray(board); 
        assertEquals(result1, result2);
    }

**Comment by Algomorph** [comment]
Thanks for reporting this, @msimmon6!  The code snippet is super-helpful when I don't have access to the student's code directly :)

**Comment by Algomorph** [comment]
I just tested this here: https://github.com/Algomorph/CodeGrader/blob/224e5fa91bab27c1e479084bb04c0fb41f7ac2e9/tests/test_module/TestModuleInheritance.test.js#L12
I haven't been able to replicate the bug as described. @msimmon6 , since I don't have access to the original students' source code, could you confirm that you're still seeing the bug with the latest version of CodeGrader, please?

**Comment by msimmon6** [comment]
I no longer see it happening -- maybe I was imagining it the whole time!
